# Generated by Django 5.0.6 on 2024-07-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.PositiveIntegerField(
                        blank=True, null=True, unique=True, verbose_name="post ID"
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="標題")),
                ("content", models.TextField(verbose_name="內文")),
                ("img", models.URLField(blank=True, null=True, verbose_name="圖片")),
                (
                    "source",
                    models.IntegerField(
                        choices=[(0, "UDN NBA")], verbose_name="來源網站"
                    ),
                ),
                ("source_url", models.URLField(unique=True, verbose_name="來源網址")),
                (
                    "post_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="推文時間"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "新聞",
                "verbose_name_plural": "新聞",
            },
        ),
    ]
