version: '3.3'

services:
  app:
    container_name: unno-app
    image: unno-app
    build: .
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    env_file:
      - ./envs/app.env
    command: sh -c "DJANGO_SETTINGS_MODULE=unno.local_settings python manage.py runserver 0.0.0.0:8000"
      # - DJANGO_SETTINGS_MODULE=unno.local_settings tail -f /dev/null
      # - DJANGO_SETTINGS_MODULE=unno.local_settings python manage.py runserver 0.0.0.0:8000
      # - DJANGO_SETTINGS_MODULE=unno.production_settings gunicorn unno.wsgi:application
    networks:
      - unno
  db:
    container_name: unno-mysql
    image: mysql:8
    env_file:
      - ./envs/db.env
    networks:
      - unno

networks:
  unno:
    name: unno
