FROM python:3.10

ENV DJANGO_SETTINGS_MODULE unno.production_settings

COPY app /app

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

RUN python manage.py collectstatic --noinput